output_folder: "outputs/test1"
analysis: "X2HDM"
year: "all"
#channels: ["mmtt", "ettt","mttt","tttt","eett","ttt","emtt"]  
channels: ["ettt"]
model_dependent: False
categories: 
        "mmtt": [[11,"mmtt_z_control_nobtag"],[12,"mmtt_2l2t_sig_nobtag"]]
        "emtt": [[11,"emtt_z_control_nobtag"],[12,"emtt_2l2t_sig_nobtag"]]
        "ettt": [[2,"ettt_nobtag"]]
        "mttt": [[2,"mttt_nobtag"]]
        "tttt": [[1,"tttt_inclusive"]]
        "eett": [[11,"eett_z_control_nobtag"],[12,"eett_2l2t_sig_nobtag"]]
        "ttt" : [[1,"ttt_inclusive"]]

variable: "mt_tot" 

background_processes:
        "mmtt": ["VVJF","VVLF","VVR","VVV","jetFakes"]
        "emtt": ["VVJF","VVLF","VVR","VVV","jetFakes"] 
        "ettt": ["VVJF","VVLF","VVR","VVV","jetFakes"]
        "mttt": ["VVJF","VVLF","VVR","VVV","jetFakes"]
        "tttt": ["VVJF","VVLF","VVR","VVV","jetFakes"]
        "eett": ["VVJF","VVLF","VVR","VVV","jetFakes"]
        "ttt" : ["VVJF","VVLF","VVR","VVV","jetFakes"]

#signal_processes: ["A60","A70","A80","A90","A100","A125","A140","A160"]
signal_processes: ["A60phi100","A60phi110","A60phi125","A60phi140","A60phi160","A60phi180","A60phi200","A60phi250","A60phi300","A60phi100","A60phi110","A60phi125","A60phi140","A60phi160","A60phi180","A60phi200","A60phi250","A60phi300","A70phi100","A70phi110","A70phi125","A70phi140","A70phi160","A70phi180","A70phi200","A70phi250","A70phi300","A80phi100","A80phi110","A80phi125","A80phi140","A80phi160","A80phi180","A80phi200","A80phi250","A80phi300","A90phi100","A90phi110","A90phi125","A90phi140","A90phi160","A90phi180","A90phi200","A90phi250","A90phi300","A100phi100","A100phi110","A100phi125","A100phi140","A100phi160","A100phi180","A100phi200","A100phi250","A100phi300","A125phi100","A125phi110","A125phi125","A125phi140","A125phi160","A125phi180","A125phi200","A125phi250","A125phi300","A140phi100","A140phi110","A140phi125","A140phi140","A140phi160","A140phi180","A140phi200","A140phi250","A140phi300","A160phi100","A160phi110","A160phi125","A160phi140","A160phi160","A160phi180","A160phi200","A160phi250","A160phi300"]

mass_shifts: ["100","110","125","140","160","180","200","250","300"]
auto_rebin: True
auto_mc: True
verbose: True 

do_systematics: False

systematics:
        Tau_ID_DM_0:
                channel: ["all"]
                effect: "shape"
                processes: ["VVJF","VVLF","VVR","VVV"]
                name: "syst_tau_id_DM0"
        
        Tau_ID_DM_1:
                channel: ["all"]
                effect: "shape"
                processes: ["VVJF","VVLF","VVR","VVV"]
                name: "syst_tau_id_DM1"

        Tau_ID_DM_10:
                channel: ["all"]
                effect: "shape"
                processes: ["VVJF","VVLF","VVR","VVV"]
                name: "syst_tau_id_DM10"

#        DoubleTau_Trigger:
#                channel: ["all"]
#                effect: "shape"
#                processes: ["VVJF","VVLF","VVR","VVV"]
#                name: "syst_doubletau_trg"
#
#        Tau_Scale_1prong:
#                channel: ["all"]
#                effect: "shape"
#                processes: ["VVJF","VVLF","VVR","VVV"]
#                name: "syst_1prong"
#
#        Tau_Scale_1prong1pizero:
#                channel: ["all"]
#                effect: "shape"
#                processes: ["VVJF","VVLF","VVR","VVV"]
#                name: "syst_1prong1pizero"
#
#        Tau_Scale_3prong:
#                channel: ["all"]
#                effect: "shape"
#                processes: ["VVJF","VVLF","VVR","VVV"]
#                name: "syst_3prong"
#
#        Tau_Scale_3prong1pizero:
#                channel: ["all"]
#                effect: "shape"
#                processes: ["VVJF","VVLF","VVR","VVV"]
#                name: "syst_3prong1pizero"

        Jet_Res:
                channel: ["all"]
                effect: "shape"
                processes: ["VVJF", "VVLF", "VVR", "VVV"]
                name: "syst_jet_res"

        Jet_Absolute:
                channel: ["all"]
                effect: "shape"
                processes: ["VVJF", "VVLF", "VVR", "VVV"]
                name: "syst_Absolute"

#        Jet_Absolute_YEAR:
#                channel: ["all"]
#                effect: "shape"
#                processes: ["VVJF", "VVLF", "VVR", "VVV"]
#                name: "syst_Absolute_YEAR"

        Jet_BBEC1:
                channel: ["all"]
                effect: "shape"
                processes: ["VVJF", "VVLF", "VVR", "VVV"]
                name: "syst_BBEC1"

#        Jet_BBEC1_YEAR:
#                channel: ["all"]
#                effect: "shape"
#                processes: ["VVJF", "VVLF", "VVR", "VVV"]
#                name: "syst_BBEC1_YEAR"

        Jet_EC2:
                channel: ["all"]
                effect: "shape"
                processes: ["VVJF", "VVLF", "VVR", "VVV"]
                name: "syst_EC2"

#        Jet_EC2_YEAR:
#                channel: ["all"]
#                effect: "shape"
#                processes: ["VVJF", "VVLF", "VVR", "VVV"]
#                name: "syst_EC2_YEAR"

        Jet_FlavorQCD:
                channel: ["all"]
                effect: "shape"
                processes: ["VVJF", "VVLF", "VVR", "VVV"]
                name: "syst_FlavorQCD"

        Jet_HF:
                channel: ["all"]
                effect: "shape"
                processes: ["VVJF", "VVLF", "VVR", "VVV"]
                name: "syst_HF"

#        Jet_HF_YEAR:
#                channel: ["all"]
#                effect: "shape"
#                processes: ["VVJF", "VVLF", "VVR", "VVV"]
#                name: "syst_HF_YEAR"

        Jet_RelativeBal:
                channel: ["all"]
                effect: "shape"
                processes: ["VVJF", "VVLF", "VVR", "VVV"]
                name: "syst_RelativeBal"

#        Jet_RelativeSample_YEAR:
#                channel: ["all"]
#                effect: "shape"
#                processes: ["VVJF", "VVLF", "VVR", "VVV"]
#                name: "syst_RelativeSample_YEAR"

        MET_Unclustered:
                channel: ["all"]
                effect: "shape"
                processes: ["VVJF","VVLF","VVR","VVV"]
                name: "syst_met_unclustered"

#        Electron_Scale:
#                channel: ["eett","ettt","emtt"]
#                effect: "shape"
#                processes: ["VVJF","VVLF","VVR","VVV"]
#                name: "syst_electron_scale"

        Jet_Fakes_iso:
                channel: ["all"]
                effect: "shape"
                processes: ["jetFakes"]
                name: "all_iso"

        Jet_Fakes_q_sum:
                channel: ["all"]
                effect: "shape"
                processes: ["jetFakes"]
                name: "all_q_sum"

        Jet_Fakes_nonclosure:
                channel: ["all"]
                effect: "shape"
                processes: ["jetFakes"]
                name: "all_non_closure"

#        Electron_ID:
#                channel: ["eett","ettt","emtt"]
#                effect: "shape"
#                processes: ["VVJF","VVLF","VVR","VVV"]
#                name: "syst_electron_id"
#
#        Muon_ID:
#                channel: ["mmtt","mttt","emtt"]
#                effect: "shape"
#                processes: ["VVJF","VVLF","VVR","VVV"]
#                name: "syst_muon_id"

        Lumi:
                channel: ["all"]
                effect: "lnN"
                processes: ["VVJF","VVLF","VVR","VVV"]
                scaleFactor: 1.016


