output_folder: "outputs/mvis1_2201"
analysis: "X2HDM"
year: "all"
#channels: ["mmtt", "emtt", "ettt","mttt","tttt","eett","ttt"]  
channels: ["tttt"]

categories: 
        "mmtt": [[1,"mmtt_inclusive"],[2,"mmtt_nobtag"],[3,"mmtt_mvis2_0-100"],[4,"mmtt_mvis2_100-200"],[5,"mmtt_mvis2_200-500"],[6,"mmtt_z_control"],[7,"mmtt_2l2t_sig"],[8,"mmtt_mvis2_0-100_2l2t_sig"],[9,"mmtt_mvis2_100-200_2l2t_sig"],[10,"mmtt_mvis2_200-500_2l2t_sig"],[11,"mmtt_z_control_nobtag"],[12,"mmtt_2l2t_sig_nobtag"]]
        "emtt": [[1,"emtt_inclusive"],[2,"emtt_nobtag"],[3,"emtt_mvis2_0-100"],[4,"emtt_mvis2_100-200"],[5,"emtt_mvis2_200-500"],[8,"emtt_mvis2_0-100_2l2t_sig"],[9,"emtt_mvis2_100-200_2l2t_sig"],[10,"emtt_mvis2_200-500_2l2t_sig"]]
        "ettt": [[1,"ettt_inclusive"],[2,"ettt_nobtag"],[3,"ettt_mvis2_0-100"],[4,"ettt_mvis2_100-200"],[5,"ettt_mvis2_200-500"],[8,"ettt_mvis2_0-100_2l2t_sig"],[9,"ettt_mvis2_100-200_2l2t_sig"],[10,"ettt_mvis2_200-500_2l2t_sig"]]
        "mttt": [[1,"mttt_inclusive"],[2,"mttt_nobtag"],[3,"mttt_mvis2_0-100"],[4,"mttt_mvis2_100-200"],[5,"mttt_mvis2_200-500"],[8,"mttt_mvis2_0-100_2l2t_sig"],[9,"mttt_mvis2_100-200_2l2t_sig"],[10,"mttt_mvis2_200-500_2l2t_sig"]]
        "tttt": [[2,"tttt_nobtag"]]
        "eett": [[1,"eett_inclusive"],[2,"eett_nobtag"],[3,"eett_mvis2_0-100"],[4,"eett_mvis2_100-200"],[5,"eett_mvis2_200-500"],[6,"eett_z_control"],[7,"eett_2l2t_sig"],[8,"eett_mvis2_0-100_2l2t_sig"],[9,"eett_mvis2_100-200_2l2t_sig"],[10,"eett_mvis2_200-500_2l2t_sig"],[11,"eett_z_control_nobtag"],[12,"eett_2l2t_sig_nobtag"]]
        "ttt" : [[1,"ttt_inclusive"],[2,"ttt_nobtag"],[3,"ttt_mvis2_0-100"],[4,"ttt_mvis2_100-200"],[5,"ttt_mvis2_200-500"],[8,"ttt_mvis2_0-100_2l2t_sig"],[9,"ttt_mvis2_100-200_2l2t_sig"],[10,"ttt_mvis2_200-500_2l2t_sig"]]

#variable: "mvis_min_sum_dR_1"
variable: "mt_tot"

background_processes:
        "mmtt": ["VVJF","VVLF","VVR","VVV","jetFakes"]
        "emtt": ["VVJF","VVLF","VVR","VVV","jetFakes"] 
        "ettt": ["VVJF","VVLF","VVR","VVV","jetFakes"]
        "mttt": ["VVJF","VVLF","VVR","VVV","jetFakes"]
        "tttt": ["VVJF","VVLF","VVR","VVV","jetFakes"]
        "eett": ["VVJF","VVLF","VVR","VVV","jetFakes"]
        "ttt" : ["VVJF","VVLF","VVR","VVV","jetFakes"]

#signal_processes: ["phi100","phi110","phi125","phi140","phi160","phi180","phi200","phi300"]
signal_processes: ["phi100","phi200"]
mass_shifts: ["60","70","80","90","100","125","140","160"]
auto_rebin: True
auto_mc: True
verbose: True 
model_dependent: True
