folder: "outputs/st_2201"
year: "all"
#channels: ["mmtt", "emtt", "ettt","mttt","tttt","eett","ttt"]  
channels: ["mmtt","eett"]

categories:
        "mmtt": [[1,"inclusive"],[2,"nobtag"]]
        "emtt": [[1,"inclusive"],[2,"nobtag"]]
        "ettt": [[1,"inclusive"],[2,"nobtag"]]
        "mttt": [[1,"inclusive"],[2,"nobtag"]]
        "tttt": [[1,"inclusive"],[2,"nobtag"]]
        "eett": [[1,"inclusive"],[2,"nobtag"]]
        "ttt" : [[1,"inclusive"],[2,"nobtag"]]
combine_categories:
        "mmtt":
                folder: "cmb_mmtt_os_ss_nobtag"
                categories: [[11,"z_control_nobtag"],[12,"2l2t_sig_nobtag"]]
        "eett":
                folder: "cmb_eett_os_ss_nobtag"
                categories: [[11,"z_control_nobtag"],[12,"2l2t_sig_nobtag"]]
        "emtt":
                folder: "cmb_emtt_mvis2"
                categories: [[3,"mvis2_0-100"],[4,"mvis2_100-200"],[5,'mvis2_200-500']]
        "ettt":
                folder: "cmb_ettt_mvis2"
                categories: [[3,"mvis2_0-100"],[4,"mvis2_100-200"],[5,'mvis2_200-500']]
        "mttt":
                folder: "cmb_mttt_mvis2"
                categories: [[3,"mvis2_0-100"],[4,"mvis2_100-200"],[5,'mvis2_200-500']]
        "tttt":
                folder: "cmb_tttt_mvis2"
                categories: [[3,"mvis2_0-100"],[4,"mvis2_100-200"],[5,'mvis2_200-500']]
        "ttt" :
                folder: "cmb_ttt_mvis2"
                categories: [[3,"mvis2_0-100"],[4,"mvis2_100-200"],[5,'mvis2_200-500']]

build_workspaces: False
build_combined_workspaces: True

calculate_AsymptoticLimits: False
calculate_combined_AsymptoticLimits: True
calculate_HybridNew: False
unblind: False

collect_limits: False
collect_combined_limits: True

grid_A: ["60","70","80","90","100","125","140","160"]
grid_phi: ["100","110","125","140","160","180","200","250","300"] 

