folder: "outputs/out_mt_tot"
year: "all"
#channels: ["cmb","mmtt", "emtt", "ettt","mttt","tttt","eett","ttt"]  
channels: ["tttt"]
build_workspaces: False
calculate_AsymptoticLimits: True
calculate_HybridNew: True
unblind: False
collect_limits: False
grid_A: ["60","70","80","90","100","125","140","160"]
grid_phi: ["100","110","125","140","160","180","200","250","300"] 
