output_folder: "outputs/1402"
analysis: "X2HDM"
year: "all"
#channels: ["mmtt", "emtt", "ettt","mttt","tttt","eett","ttt"]  
channels: ["mmtt"]
categories: 
        "mmtt": [[1,"mmtt_inclusive"]]
        "emtt": [[11,"emtt_z_control_nobtag"],[12,"emtt_2l2t_sig_nobtag"]]
        "ettt": [[2,"ettt_nobtag"]]
        "mttt": [[2,"mttt_nobtag"]]
        "tttt": [[1,"tttt_inclusive"]]
        "eett": [[11,"eett_z_control_nobtag"],[12,"eett_2l2t_sig_nobtag"]]
        "ttt" : [[1,"ttt_inclusive"]]

#        "mmtt": [[1,"mmtt_inclusive"],[2,"mmtt_nobtag"],[11,"mmtt_z_control_nobtag"],[12,"mmtt_2l2t_sig_nobtag"]]
#        "emtt": [[1,"emtt_inclusive"],[2,"emtt_nobtag"],[11,"emtt_z_control_nobtag"],[12,"emtt_2l2t_sig_nobtag"]]
#        "ettt": [[1,"ettt_inclusive"],[2,"ettt_nobtag"]]
#        "mttt": [[1,"mttt_inclusive"],[2,"mttt_nobtag"]]
#        "tttt": [[1,"tttt_inclusive"],[2,"tttt_nobtag"]]
#        "eett": [[1,"eett_inclusive"],[2,"eett_nobtag"],[11,"eett_z_control_nobtag"],[12,"eett_2l2t_sig_nobtag"]]
#        "ttt" : [[1,"ttt_inclusive"],[2,"ttt_nobtag"]]


variable: "mt_tot"

background_processes:
        "mmtt": ["VVJF","VVLF","VVR","VVV","jetFakes"]
        "emtt": ["VVJF","VVLF","VVR","VVV","jetFakes"] 
        "ettt": ["VVJF","VVLF","VVR","VVV","jetFakes"]
        "mttt": ["VVJF","VVLF","VVR","VVV","jetFakes"]
        "tttt": ["VVJF","VVLF","VVR","VVV","jetFakes"]
        "eett": ["VVJF","VVLF","VVR","VVV","jetFakes"]
        "ttt" : ["VVJF","VVLF","VVR","VVV","jetFakes"]

signal_processes: ["A60phi","A70phi","A80phi","A90phi","A100phi","A125phi","A140phi","A160phi"]
mass_shifts: ["100","110","125","140","160","180","200","250","300"]
auto_rebin: True
auto_mc: True
verbose: True 

systematics:
        Tau_ID_DM_0:
                channel: "all"
                effect: "shape"
                processes: ["VVJF","VVLF","VVR","VVV"]
                name: "syst_tau_id_DM0"
        
        Tau_ID_DM_1:
                channel: "all"
                effect: "shape"
                processes: ["VVJF","VVLF","VVR","VVV"]
                name: "syst_tau_id_DM1"

        Tau_ID_DM_10:
                channel: "all"
                effect: "shape"
                processes: ["VVJF","VVLF","VVR","VVV"]
                name: "syst_tau_id_DM10"

        DoubleTau_Trigger:
                channel: "all"
                effect: "shape"
                processes: ["VVJF","VVLF","VVR","VVV"]
                name: "syst_doubletau_trg"

        Tau_Scale_1prong:
                channel: "all"
                effect: "shape"
                processes: ["VVJF","VVLF","VVR","VVV"]
                name: "1prong"

        Tau_Scale_1prong1pizero:
                channel: "all"
                effect: "shape"
                processes: ["VVJF","VVLF","VVR","VVV"]
                name: "1prong1pizero"

        Tau_Scale_3prong:
                channel: "all"
                effect: "shape"
                processes: ["VVJF","VVLF","VVR","VVV"]
                name: "3prong"

        Tau_Scale_3prong1pizero:
                channel: "all"
                effect: "shape"
                processes: ["VVJF","VVLF","VVR","VVV"]
                name: "3prong1pizero"

        Jet_Res:
                channel: "all"
                effect: "shape"
                processes: ["VVJF", "VVLF", "VVR", "VVV"]
                name: "syst_jet_res"

        Jet_Absolute:
                channel: "all"
                effect: "shape"
                processes: ["VVJF", "VVLF", "VVR", "VVV"]
                name: "Absolute"

        Jet_Absolute_YEAR:
                channel: "all"
                effect: "shape"
                processes: ["VVJF", "VVLF", "VVR", "VVV"]
                name: "Absolute_YEAR"

        Jet_BBEC1:
                channel: "all"
                effect: "shape"
                processes: ["VVJF", "VVLF", "VVR", "VVV"]
                name: "BBEC1"

        Jet_BBEC1_YEAR:
                channel: "all"
                effect: "shape"
                processes: ["VVJF", "VVLF", "VVR", "VVV"]
                name: "BBEC1_YEAR"

        Jet_EC2:
                channel: "all"
                effect: "shape"
                processes: ["VVJF", "VVLF", "VVR", "VVV"]
                name: "EC2"

        Jet_EC2_YEAR:
                channel: "all"
                effect: "shape"
                processes: ["VVJF", "VVLF", "VVR", "VVV"]
                name: "EC2_YEAR"

        Jet_FlavorQCD:
                channel: "all"
                effect: "shape"
                processes: ["VVJF", "VVLF", "VVR", "VVV"]
                name: "FlavorQCD"

        Jet_HF:
                channel: "all"
                effect: "shape"
                processes: ["VVJF", "VVLF", "VVR", "VVV"]
                name: "HF"

        Jet_HF_YEAR:
                channel: "all"
                effect: "shape"
                processes: ["VVJF", "VVLF", "VVR", "VVV"]
                name: "HF_YEAR"

        Jet_RelativeBal:
                channel: "all"
                effect: "shape"
                processes: ["VVJF", "VVLF", "VVR", "VVV"]
                name: "RelativeBal"

        Jet_RelativeSample_YEAR:
                channel: "all"
                effect: "shape"
                processes: ["VVJF", "VVLF", "VVR", "VVV"]
                name: "RelativeSample_YEAR"

        MET_Unclustered:
                channel: "all"
                effect: "shape"
                processes: ["VVJF","VVLF","VVR","VVV"]
                name: "syst_met_unclustered"

#        Electron_Scale:
#                channel: ""
#                effect: "shape"
#                processes: ["VVJF","VVLF","VVR","VVV"]
#                name: "syst_electron_scale"
#
        Jet_Fakes_iso:
                channel: "all"
                effect: "shape"
                processes: ["jetFakes"]
                name: "all_iso"

        Jet_Fakes_q_sum:
                channel: "all"
                effect: "shape"
                processes: ["jetFakes"]
                name: "all_q_sum"

        Jet_Fakes_nonclosure:
                channel: "all"
                effect: "shape"
                processes: ["jetFakes"]
                name: "all_non_closure"

        Lumi:
                channel: "all"
                effect: "lnN"
                processes: ["VVJF","VVLF","VVR","VVV"]
                scaleFactor: 1.016

               
              









