output_folder: "outputs/out_1012"
analysis: "X2HDM"
year: "all"
channels: ["mmtt", "emtt", "ettt","mttt","tttt","eett"]  

categories: 
        "mmtt": [[1,"mmtt_inclusive"]]
        "emtt": [[1,"emtt_inclusive"]]
        "ettt": [[1,"ettt_inclusive"]]
        "mttt": [[1,"mttt_inclusive"]]
        "tttt": [[1,"tttt_inclusive"]]
        "eett": [[1,"eett_inclusive"]]

variable: "mvis_min_sum_dR_1"

background_processes:
        "mmtt": ["VVJF","VVLF","VVR","VVV","WGam","WJF","WLF","WR","ZJF","ZLF","ZR","jetFakes"]
        "emtt": ["VVJF","VVLF","VVR","VVV","WGam","WJF","WLF","WR","ZJF","ZLF","ZR","jetFakes"] 
        "ettt": ["VVJF","VVLF","VVR","VVV","WGam","WJF","WLF","WR","ZJF","ZLF","ZR","jetFakes"]
        "mttt": ["VVJF","VVLF","VVR","VVV","WGam","WJF","WLF","WR","ZJF","ZLF","ZR","jetFakes"]
        "tttt": ["VVJF","VVLF","VVR","VVV","WGam","WJF","WLF","WR","ZJF","ZLF","ZR","jetFakes"]
        "eett": ["VVJF","VVLF","VVR","VVV","WGam","WJF","WLF","WR","ZJF","ZLF","ZR","jetFakes"]

signal_processes: ["A60phi","A70phi","A80phi","A90phi","A100phi","A125phi","A140phi","A160phi"]
mass_shifts: ["100","110","125","140","160","180","200","250","300"]
auto_rebin: False
auto_mc: True
verbose: True 
 
